image: ghcr.io/kogeletey/karzok:bdf09c75cc235222f2666de4f69145f8b5b5dd7f

pages:
  script:
    - sh /www/build.sh
    - mv /www/public public
  only:
   - develop
  artifacts:
    paths:
      - public/
