title = "Re128 | Karzok"

base_url = "https://karzok.re128.org"
theme = "karzok"

description = "The theme for launching fast documentation sites"

default_language = "en"

build_search_index = true

minify_html = true

compile_sass = true

[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = [
    "http://localhost:8080",
    "http://127.0.0.1:1111"
]

[search]
include_title = true
include_description = false
include_content = true

[slugify]
paths = "safe"
anchors = "on"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

render_emoji = true

[extra]
# logotype
favicon = "assets/favicon.ico"

# header title
header.name = "Karzok"

show_word_count = true
show_reading_time = true
relative_path = true

repo = "https://github.com/kogeletey/nebra"
repo_branch = "prod"

announcement_file = "content/announcement.toml"

[[extra.header_left]]
text = "Reference"
link = "@/reference"

[[extra.header_right]]
link = "https://github.com/kogeletey/karzok"
svg = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2A10 10 0 0 0 2 12c0 4.42 2.87 8.17 6.84 9.5c.5.08.66-.23.66-.5v-1.69c-2.77.6-3.36-1.34-3.36-1.34c-.46-1.16-1.11-1.47-1.11-1.47c-.91-.62.07-.6.07-.6c1 .07 1.53 1.03 1.53 1.03c.87 1.52 2.34 1.07 2.91.83c.09-.65.35-1.09.63-1.34c-2.22-.25-4.55-1.11-4.55-4.92c0-1.11.38-2 1.03-2.71c-.1-.25-.45-1.29.1-2.64c0 0 .84-.27 2.75 1.02c.79-.22 1.65-.33 2.5-.33c.85 0 1.71.11 2.5.33c1.91-1.29 2.75-1.02 2.75-1.02c.55 1.35.2 2.39.1 2.64c.65.71 1.03 1.6 1.03 2.71c0 3.82-2.34 4.66-4.57 4.91c.36.31.69.92.69 1.85V21c0 .27.16.59.67.5C19.14 20.16 22 16.42 22 12A10 10 0 0 0 12 2z" fill="currentColor"></path></svg>'

[[extra.header_right]]
link = "https://codeberg.org/kogeletey/karzok"
svg = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M11.955.49A12 12 0 0 0 0 12.49a12 12 0 0 0 1.832 6.373L11.838 5.928a.187.14 0 0 1 .324 0l10.006 12.935A12 12 0 0 0 24 12.49a12 12 0 0 0-12-12a12 12 0 0 0-.045 0zm.375 6.467l4.416 16.553a12 12 0 0 0 5.137-4.213z"/></svg>'

[[extra.footer]]
text = "powered by <a href=\"https://karzok.re128.org\"> karzok</a>"

[[extra.footer]]
version = "https://api.github.com/repos/kogeletey/karzok/releases/latest"

[[extra.menu]]
text = "Install"
link = "$base_url/install"

[[extra.menu]]
text = "Configure"
link = "$base_url/configure"

[[extra.menu]]
text = "Contribute"
link = "$base_url/contribute"

